/// Flutter icons LS
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LS
///      fonts:
///       - asset: fonts/LS.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LS {
  LS._();

  static const _kFontFam = 'LS';

  static const IconData search = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData password = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData install = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData address = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData my = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData search1 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData return_icon = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData fanhui = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData ellipsis = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData icon_quanquan = const IconData(0xe80a, fontFamily: _kFontFam);
}
