/// Flutter icons MyArrow
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyArrow
///      fonts:
///       - asset: fonts/MyArrow.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyArrow {
  MyArrow._();

  static const _kFontFam = 'MyArrow';

  static const IconData arrow_ = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData arrow_1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData fangxiangjiantou_xiangyou = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData fangxiangjiantou_xiangzuo = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData fangxiang_xiangxia = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData fangxiang_xiangshang = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData fangxiang_xiangzuo = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData fangxiang_xiangyou = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData fangxiangyuan_xiangshang = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData fangxiangyuan_xiangxia = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData fangxiangyuan_xiangyou = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData fangxiangyuan_xiangzuo = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData fangxiangyuanjiantou_xiangyou = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData fangxiangyuanjiantou_xiangshang = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData fangxiangyuanjiantou_xiangxia = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData fangxiangyuanjiantou_xiangzuo = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData fangxiangsanjiao_xiangshang = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData fangxiangsanjiao_xiangyou = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData fangxiangsanjiao_xiangxia = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData fangxiangsanjiao_xiangzuo = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData arrow_2 = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData arrow = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData arrow_3 = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData arrow_4 = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData arrow1 = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData arrow2 = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData arrow_5 = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData arrow_6 = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData arrow_7 = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData arrow_8 = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData arrow_9 = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData arrow_10 = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData arrow_11 = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData arrow_12 = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData arrow_13 = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData arrow_14 = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData arrow_15 = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData arrow_16 = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData arrow_17 = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData arrow_18 = const IconData(0xe827, fontFamily: _kFontFam);
}
