/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData icon_ = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData icon_1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData icon_2 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData icon_3 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData icon_4 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData icon_5 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData icon_6 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData icon_7 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData icon_8 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData icon_9 = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData icon_10 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData icon_11 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData icon_12 = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData icon_13 = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData icon_14 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData icon_15 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData icon_16 = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData icon_17 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData icon_18 = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData icon_scan = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData icon_search = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData icon_edit = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData icon_set = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData icon_voice = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData icon_heart = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData icon_star = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData icon_board = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData icon_folder = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData icon_clock = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData icon_bar = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData icon_setting = const IconData(0xe81e, fontFamily: _kFontFam);
}
