/// Flutter icons MyHome
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyHome
///      fonts:
///       - asset: fonts/MyHome.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyHome {
  MyHome._();

  static const _kFontFam = 'MyHome';

  static const IconData caidan = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData xiazai = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData faxian = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData shoucang = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bianji = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData yonghu = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData gengduo = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData shezhi = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData quxiao = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData zuojiantou = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData mima = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData youjiantou = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData saoyisao = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData xiajiantou = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData shangchuan = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData xiaoxi = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData fenlei = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData kefu = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData fenxiang = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData junhengqi = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData dingwei = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData biaoqian = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData shangjiantou = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData zhuye = const IconData(0xe817, fontFamily: _kFontFam);
}
